# legacy v2 http server (optional)
http_v2 = 17732

[[nodes]]
# name of the node, used in http requests as parameter `node_name`
# for example: `http://localhost:17732/v2/p2p?node_name=tezedge&limit=1000`
name = "tezedge"
# new v3 http server (optional)
http_v3 = 17742
# path to db
db = "./target/debugger_db"
# path to search identity at
# debugger expect the node will listen its p2p incoming connections on this port
# the process which bind a socket on this port first, will be considered as the node
# this is an inner port inside docker's virtual network of the node's container
p2p = { identity = "../tezedge/light_node/etc/tezedge/identity.json", port = 9732 }
# debugger will run syslog server on this port
# this is an inner port inside docker's virtual network of the debugger's container
log = { port = 10000 }
