[package]
name = "tezedge-recorder"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@simplestaking.com>"]
edition = "2018"

[lib]
doctest = false

[[bin]]
name = "tezedge-recorder"
path = "src/bin/main.rs"

[dependencies]
toml = "0.5"
serde = "1.0"
serde_json = "1.0"
hex = "0.4"
rocksdb = "0.15"
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
either = "1.6"
typenum = "1.13"
syslog_loose = "0.14"
itertools = "0.10"

ctrlc = "3.1"
tracing-subscriber = "0.2"
tracing = "0.1"

warp = "0.3"
tokio = { version = "1.8", features = ["rt-multi-thread"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.3", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
bpf-recorder = { path = "../bpf-recorder", features = ["client"] }

crypto = { tag = "v1.6.5", git = "https://github.com/tezedge/tezedge" }
tezos_messages = { tag = "v1.6.5", git = "https://github.com/tezedge/tezedge" }
storage = { tag = "v1.6.5", git = "https://github.com/tezedge/tezedge" }
#crypto = { path = "../../tezedge/crypto" }
#tezos_messages = { path = "../../tezedge/tezos/messages" }
#storage = { path = "../../tezedge/storage" }
